import jsPDF from "jspdf";
import { siteConfig } from "./site";

export interface EstimateData {
  linearFeet: number;
  gates: number;
  materialCostPerFt: number;
  laborCostPerFt: number;
  targetMargin: number;
  totalMaterialCost: number;
  totalLaborCost: number;
  totalCost: number;
  suggestedSalePrice: number;
  actualMargin: number;
}

function fmt(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

export function generateEstimatePDF(data: EstimateData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(siteConfig.name, 20, 25);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Fence Estimate", 20, 32);
  doc.text(new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }), 20, 38);

  doc.setDrawColor(200, 200, 200);
  doc.line(20, 44, pageWidth - 20, 44);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Job Details", 20, 56);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const inputs = [
    ["Linear Feet", `${data.linearFeet} ft`],
    ["Gates", `${data.gates}`],
    ["Material Cost / ft", fmt(data.materialCostPerFt)],
    ["Labor Cost / ft", fmt(data.laborCostPerFt)],
    ["Target Margin", `${data.targetMargin}%`],
  ];

  let y = 66;
  inputs.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(label, 20, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text(value, pageWidth - 20, y, { align: "right" });
    y += 8;
  });

  y += 4;
  doc.line(20, y, pageWidth - 20, y);
  y += 14;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Estimate Breakdown", 20, y);
  y += 12;

  const results = [
    ["Estimated Material Cost", fmt(data.totalMaterialCost), false],
    ["Estimated Labor Cost", fmt(data.totalLaborCost), false],
    ["Total Job Cost", fmt(data.totalCost), true],
    ["Suggested Sale Price", fmt(data.suggestedSalePrice), true],
  ] as const;

  results.forEach(([label, value, bold]) => {
    doc.setFontSize(11);
    if (bold) {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
    } else {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
    }
    doc.text(label, 20, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text(value, pageWidth - 20, y, { align: "right" });
    y += 9;
  });

  y += 8;
  const isBelowTarget = data.actualMargin < data.targetMargin;
  const marginDisplay = `${data.actualMargin.toFixed(1)}%`;

  if (isBelowTarget) {
    doc.setFillColor(254, 226, 226);
    doc.roundedRect(20, y - 6, pageWidth - 40, 28, 4, 4, "F");
    doc.setTextColor(185, 28, 28);
  } else {
    doc.setFillColor(220, 252, 231);
    doc.roundedRect(20, y - 6, pageWidth - 40, 28, 4, 4, "F");
    doc.setTextColor(21, 128, 61);
  }

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("ACTUAL GROSS MARGIN", pageWidth / 2, y + 2, { align: "center" });

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(marginDisplay, pageWidth / 2, y + 16, { align: "center" });

  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(
    `Generated by ${siteConfig.name} — ${siteConfig.url}`,
    pageWidth / 2,
    footerY,
    { align: "center" }
  );

  doc.save("fence-estimate.pdf");
}
