"use server";
// ── Convert FenceGraph BOM → Standard Estimate ────────────────────
// Bridges the advanced estimation engine output into the regular
// estimate workflow: BOM line items → estimate record → redirect to
// estimate detail page where contractor can review, send, and get signed.

import { createClient, createAdminClient } from "@/lib/supabase/server";
import { RateLimiters } from "@/lib/security/rate-limit";
import { enforceBillingGate } from "@/lib/subscription";
import { getOrgMarginTargets, marginStatus } from "@/lib/marginTargets";
import type { FenceEstimateResult } from "@/lib/fence-graph/types";

interface ConvertInput {
  result: FenceEstimateResult;
  projectName: string;
  laborRate: number;
  markupPct: number;
  totalLF: number;
  fenceType: string;
  customer: {
    name: string;
    address: string;
    city: string;
    phone: string;
    email: string;
  };
}

export async function createEstimateFromFenceGraph(
  input: ConvertInput
): Promise<{ success: boolean; estimateId?: string; error?: string }> {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { success: false, error: "Not authenticated" };

    const admin = createAdminClient();
    const { data: profile } = await admin
      .from("profiles").select("id, org_id").eq("auth_id", user.id).single();
    if (!profile) return { success: false, error: "Profile not found" };

    // ✅ BILLING: Subscription + monthly cap gate.
    const billingBlock = await enforceBillingGate(profile.org_id);
    if (billingBlock) return billingBlock;

    // ✅ SECURITY: Rate limit estimate conversion (creates DB records)
    const rateLimit = RateLimiters.estimateCreation(profile.org_id);
    if (!rateLimit.success) {
      return { success: false, error: rateLimit.error ?? "Rate limit exceeded. Please try again later." };
    }

    const { result, projectName, laborRate, markupPct, totalLF, fenceType, customer } = input;
    const bidPrice = Math.round(result.totalCost * (1 + markupPct / 100));
    const grossProfit = bidPrice - result.totalCost;
    // Store as decimal (0.259) to match the format used by createEstimate/sendQuote
    const grossMarginPct = bidPrice > 0 ? Math.round((grossProfit / bidPrice) * 1000) / 1000 : 0;
    // margin_status bucket follows the org's configured target from Settings
    // rather than a hardcoded 30%/20% split. So a Pearl Labs estimate with
    // margin at 33% correctly reads "warning" if their target is 35%, not "good".
    const marginTargets = await getOrgMarginTargets(profile.org_id);

    // ── 1. Create or find customer ──────────────────────────────────
    let customerId: string | null = null;
    if (customer.name.trim()) {
      // Check if customer already exists (by name + org)
      const { data: existing } = await admin
        .from("customers")
        .select("id")
        .eq("org_id", profile.org_id)
        .ilike("name", customer.name.trim())
        .limit(1)
        .single();

      if (existing) {
        customerId = existing.id;
      } else {
        const { data: newCust, error: custErr } = await admin
          .from("customers")
          .insert({
            org_id: profile.org_id,
            name: customer.name.trim(),
            phone: customer.phone || null,
            address: customer.address || null,
            email: customer.email || null,
          })
          .select("id")
          .single();

        if (custErr) return { success: false, error: `Customer creation failed: ${custErr.message}` };
        customerId = newCust.id;
      }
    }

    if (!customerId) {
      return { success: false, error: "Customer name is required to create an estimate." };
    }

    // ── 2. Create estimate record ────────────────────────────────────
    const { data: est, error: estErr } = await admin
      .from("estimates")
      .insert({
        org_id: profile.org_id,
        created_by: profile.id,
        customer_id: customerId,
        title: projectName,
        status: "draft",
        fence_type: fenceType,
        linear_feet: totalLF,
        gate_count: result.bom.filter(b => b.category === "gates").reduce((s, b) => s + b.qty, 0),
        post_spacing: 8,
        height: 6,
        waste_factor_pct: result.probabilisticWastePct,  // decimal (0.05), matches createEstimate format
        target_margin_pct: grossMarginPct,              // decimal (0.259), NOT markup% — matches sendQuote margin guard
        labor_rate_per_hr: laborRate,
        total: bidPrice,
        margin_pct: grossMarginPct,
        materials_subtotal: result.totalMaterialCost,
        labor_subtotal: result.totalLaborCost,
        estimated_cost: result.totalCost,
        gross_profit: grossProfit,
        gross_margin_pct: grossMarginPct,
        margin_status: marginStatus(grossMarginPct, marginTargets),
        notes: `Generated by FenceGraph Advanced Estimator. Confidence: ${Math.round((result.overallConfidence ?? 0) * 100)}%. Total LF: ${totalLF}. ${result.bom.length} BOM line items.`,
      })
      .select("id")
      .single();

    if (estErr) return { success: false, error: `Estimate creation failed: ${estErr.message}` };

    // ── 3. Insert BOM as line items ──────────────────────────────────
    const materialRows = result.bom
      .filter(item => item.qty > 0)
      .map((item, idx) => {
        const unitPrice = item.unitCost != null ? Math.round(item.unitCost * (1 + markupPct / 100) * 100) / 100 : 0;
        const extendedCost = item.extCost ?? 0;
        const extendedPrice = unitPrice * item.qty;
        return {
          estimate_id: est.id,
          org_id: profile.org_id,
          sku: item.sku,
          description: item.name,
          quantity: item.qty,
          unit: item.unit,
          unit_cost: item.unitCost ?? 0,
          unit_price: unitPrice,
          extended_cost: extendedCost,
          extended_price: extendedPrice,
          total: extendedPrice,
          type: "material" as const,
          sort_order: idx,
          meta: JSON.stringify({ category: item.category, traceability: item.traceability, confidence: item.confidence }),
        };
      });

    // Labor line item
    const laborUnitPrice = result.totalLaborHrs > 0
      ? Math.round((result.totalLaborCost / result.totalLaborHrs) * (1 + markupPct / 100) * 100) / 100
      : 0;

    materialRows.push({
      estimate_id: est.id,
      org_id: profile.org_id,
      sku: "",
      description: `Labor — ${result.totalLaborHrs}h @ $${laborRate}/hr (${result.laborDrivers.filter(l => l.count > 0).map(l => `${l.activity}: ${l.totalHrs.toFixed(1)}h`).join(", ")})`,
      quantity: result.totalLaborHrs,
      unit: "hr",
      unit_cost: laborRate,
      unit_price: laborUnitPrice,
      extended_cost: result.totalLaborCost,
      extended_price: Math.round(laborUnitPrice * result.totalLaborHrs),
      total: Math.round(laborUnitPrice * result.totalLaborHrs),
      type: "material" as const,
      sort_order: materialRows.length,
      meta: JSON.stringify({ source: "FenceGraph", laborDrivers: result.laborDrivers }),
    });

    if (materialRows.length > 0) {
      const { error: lineErr } = await admin
        .from("estimate_line_items")
        .insert(materialRows);

      if (lineErr) {
        // Non-fatal — estimate was created, line items failed
        console.error("Line items insert error:", lineErr);
      }
    }

    return { success: true, estimateId: est.id };
  } catch (err: unknown) {
    return { success: false, error: err instanceof Error ? err.message : "Conversion failed" };
  }
}
