"use server";
// ── Convert FenceGraph BOM → Standard Estimate ────────────────────
// Bridges the advanced estimation engine output into the regular
// estimate workflow: BOM line items → estimate record → redirect to
// estimate detail page where contractor can review, send, and get signed.

import type { FenceEstimateResult, FenceProjectInput, FenceType, WoodStyle } from "@/lib/fence-graph/engine";
import { recomputeEstimateForOrg, requireOrgEstimateContext } from "./serverEstimate";

interface ConvertInput {
  input: FenceProjectInput;
  result?: FenceEstimateResult;
  projectName: string;
  laborRate: number;
  markupPct: number;
  wastePct: number;
  fenceType: FenceType;
  woodStyle?: WoodStyle;
  customer: {
    name: string;
    address: string;
    city: string;
    phone: string;
    email: string;
  };
}

export async function createEstimateFromFenceGraph(
  input: ConvertInput
): Promise<{ success: boolean; estimateId?: string; error?: string }> {
  try {
    const context = await requireOrgEstimateContext();
    if (!context) return { success: false, error: "Not authenticated" };

    const { input: projectInput, projectName, laborRate, markupPct, wastePct, fenceType, woodStyle, customer } = input;
    const { result, totalLF } = await recomputeEstimateForOrg(context, {
      input: projectInput,
      laborRate,
      wastePctPercent: wastePct,
      fenceType,
      woodStyle,
    });
    const bidPrice = Math.round(result.totalCost * (1 + markupPct / 100));
    const grossProfit = bidPrice - result.totalCost;
    const grossMarginPct = bidPrice > 0 ? Math.round((grossProfit / bidPrice) * 100) : 0;

    let customerId: string | null = null;
    if (customer.name.trim()) {
      const { data: existing } = await context.admin
        .from("customers")
        .select("id")
        .eq("org_id", context.orgId)
        .ilike("name", customer.name.trim())
        .limit(1)
        .single();

      if (existing) {
        customerId = existing.id;
      } else {
        const { data: newCust, error: custErr } = await context.admin
          .from("customers")
          .insert({
            org_id: context.orgId,
            name: customer.name.trim(),
            phone: customer.phone || null,
            address: customer.address || null,
            email: customer.email || null,
          })
          .select("id")
          .single();

        if (custErr) return { success: false, error: `Customer creation failed: ${custErr.message}` };
        customerId = newCust.id;
      }
    }

    if (!customerId) {
      return { success: false, error: "Customer name is required to create an estimate." };
    }

    const { data: est, error: estErr } = await context.admin
      .from("estimates")
      .insert({
        org_id: context.orgId,
        created_by: context.profileId,
        customer_id: customerId,
        title: projectName,
        status: "draft",
        fence_type: fenceType,
        linear_feet: totalLF,
        gate_count: result.bom.filter((item) => item.category === "gates").reduce((sum, item) => sum + item.qty, 0),
        post_spacing: 8,
        height: projectInput.fenceHeight,
        waste_factor_pct: Math.round(result.probabilisticWastePct * 100),
        target_margin_pct: markupPct,
        labor_rate_per_hr: laborRate,
        total: bidPrice,
        margin_pct: grossMarginPct,
        materials_subtotal: result.totalMaterialCost,
        labor_subtotal: result.totalLaborCost,
        estimated_cost: result.totalCost,
        gross_profit: grossProfit,
        gross_margin_pct: grossMarginPct,
        margin_status: grossMarginPct >= 30 ? "good" : grossMarginPct >= 20 ? "warning" : "low",
        notes: `Generated by FenceGraph Advanced Estimator. Confidence: ${Math.round((result.overallConfidence ?? 0) * 100)}%. Total LF: ${totalLF}. ${result.bom.length} BOM line items.`,
      })
      .select("id")
      .single();

    if (estErr) return { success: false, error: `Estimate creation failed: ${estErr.message}` };

    const materialRows = result.bom
      .filter((item) => item.qty > 0)
      .map((item, idx) => {
        const unitPrice = item.unitCost != null ? Math.round(item.unitCost * (1 + markupPct / 100) * 100) / 100 : 0;
        const extendedCost = item.extCost ?? 0;
        const extendedPrice = unitPrice * item.qty;
        return {
          estimate_id: est.id,
          org_id: context.orgId,
          sku: item.sku,
          description: item.name,
          quantity: item.qty,
          unit: item.unit,
          unit_cost: item.unitCost ?? 0,
          unit_price: unitPrice,
          extended_cost: extendedCost,
          extended_price: extendedPrice,
          total: extendedPrice,
          type: "material" as const,
          sort_order: idx,
          meta: JSON.stringify({ category: item.category, traceability: item.traceability, confidence: item.confidence }),
        };
      });

    const laborUnitPrice = result.totalLaborHrs > 0
      ? Math.round((result.totalLaborCost / result.totalLaborHrs) * (1 + markupPct / 100) * 100) / 100
      : 0;

    materialRows.push({
      estimate_id: est.id,
      org_id: context.orgId,
      sku: "",
      description: `Labor — ${result.totalLaborHrs}h @ $${laborRate}/hr (${result.laborDrivers.filter((driver) => driver.count > 0).map((driver) => `${driver.activity}: ${driver.totalHrs.toFixed(1)}h`).join(", ")})`,
      quantity: result.totalLaborHrs,
      unit: "hr",
      unit_cost: laborRate,
      unit_price: laborUnitPrice,
      extended_cost: result.totalLaborCost,
      extended_price: Math.round(laborUnitPrice * result.totalLaborHrs),
      total: Math.round(laborUnitPrice * result.totalLaborHrs),
      type: "material" as const,
      sort_order: materialRows.length,
      meta: JSON.stringify({ source: "FenceGraph", laborDrivers: result.laborDrivers }),
    });

    if (materialRows.length > 0) {
      const { error: lineErr } = await context.admin
        .from("estimate_line_items")
        .insert(materialRows);

      if (lineErr) {
        await context.admin.from("estimates").delete().eq("id", est.id).eq("org_id", context.orgId);
        return { success: false, error: `Estimate line item creation failed: ${lineErr.message}` };
      }
    }

    return { success: true, estimateId: est.id };
  } catch (err: unknown) {
    return { success: false, error: err instanceof Error ? err.message : "Conversion failed" };
  }
}
