/**
 * AR Quote — Zod validation schemas for /api/ar/* routes.
 *
 * These shape the inputs to the three AR endpoints:
 *   - GET  /api/ar/assets             → ARAssetsQuerySchema
 *   - POST /api/ar/sessions           → ARSessionCreateSchema
 *   - PATCH /api/ar/sessions/[id]     → ARSessionUpdateSchema
 *
 * Token fields are UUIDs (same format as fence_graphs.public_token,
 * generated by the existing generate_quote_token SQL function). All
 * enum values match the CHECK constraints on public.ar_sessions so
 * validation rejects anything the DB would reject anyway — with a
 * cleaner error before we burn a RPC roundtrip.
 */

import { z } from "zod";

// ── GET /api/ar/assets ────────────────────────────────────────────
export const ARAssetsQuerySchema = z.object({
  token: z.string().uuid("Invalid token format"),
});
export type ARAssetsQuery = z.infer<typeof ARAssetsQuerySchema>;

// ── POST /api/ar/sessions ─────────────────────────────────────────
export const ARSessionCreateSchema = z.object({
  token: z.string().uuid("Invalid token format"),
  launchedBy: z.enum(["contractor", "customer"]),
  deviceType: z.enum(["ios", "android", "desktop", "unknown"]).optional(),
  arMode: z.enum(["quick_look", "scene_viewer", "webxr", "fallback_3d"]).optional(),
  userAgent: z.string().max(500).optional(),
});
export type ARSessionCreateInput = z.infer<typeof ARSessionCreateSchema>;

// ── PATCH /api/ar/sessions/[session_id] ───────────────────────────
// All lifecycle fields are optional — a typical PATCH will update
// one (status) or two (status + a timestamp). publicToken proves
// session ownership for the anon customer path; the contractor path
// relies on auth + org match.
export const ARSessionUpdateSchema = z.object({
  status: z
    .enum(["launched", "placed", "screenshot_taken", "abandoned", "completed"])
    .optional(),
  arLaunchedAt: z.string().datetime().optional(),
  firstPlacedAt: z.string().datetime().optional(),
  completedAt: z.string().datetime().optional(),
  durationSeconds: z.number().int().min(0).max(3600).optional(),
  publicToken: z.string().uuid().optional(),
});
export type ARSessionUpdateInput = z.infer<typeof ARSessionUpdateSchema>;
